### ISSUE TITLE
No need to have an empty default constructor

### ISSUE THREAD

**Issue by mayisa87** [andulica/QuizzMaker#20]
https://github.com/andulica/QuizzMaker/blob/68d147d7098b4118f109b3b2e4d1ae11303ba17f/Question.cs#L8-L10

Usually for XML export it is only important that the class itself is public and not set to internal. There is no need to have an default constructor implemented, as it is anyway empty :) Try if it still works without it.

**Comment by andulica** [comment]
For some reason the code refactor  (replacing the hard coded values with constants) that was meant for the previous issue #19 was also executed on this commit. Apologies

**Comment by andulica** [comment]
Apparently I am getting an error when I try to play questions from a file. I get the following error:

System.InvalidOperationException
  HResult=0x80131509
  Message=QuizMakerProgram.Question cannot be serialized because it does not have a parameterless constructor.
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError)
   at System.Xml.Serialization.ModelScope.GetTypeModel(Type type, Boolean directReference)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at QuizMakerProgram.Quiz.Deserialize(String filePath)
   at QuizMakerProgram.QuizEditor.SelectQuizToPlay()
   at ConsoleApp1.Program.Main(String[] args)

**Comment by mayisa87** [comment]
I think if you got no constructor at all, it works, but as you use an paramterized constructor too, the XML Serialization needs the default constructor too. 

But it is not so nice having this empty constructor just to avoid the error message. So better delete both constructors and try if it works, changing these line:

https://github.com/andulica/QuizzMaker/blob/6e9919af5580b9ed45d2459c270343b0b0d4586d/GUI.cs#L140

Just use Question question = new Question();

and set the values by their properties.
